name: Deploy to vercel on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    if: github.repository == 'lokari-unesa/lokari'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - uses: amondnet/vercel-action@v42
        with:
          working-directory: frontend
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-deployment: true
          vercel-args: '--prod --yes'
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}